version: '3.8'

services:
  proxy:
    build: .
    container_name: proxyx
    restart: always
    
    # Host 模式直接使用宿主机端口
    network_mode: "host"

    environment:
      # --- 基础配置 ---
      - PORT=21011
      - PASSWORD=123456
      - MAX_REDIRECTS=5
      - ENABLE_CACHE=true
      - CACHE_TTL=3600
      
      # --- 访问控制 ---
      - BLACKLIST=
      - WHITELIST=
      - ALLOW_IPS=
      - ALLOW_COUNTRIES=
      
      # --- 额度与权限 ---
      - DAILY_LIMIT_COUNT=200
      - ADMIN_IPS=127.0.0.1
      - IP_LIMIT_WHITELIST=127.0.0.1
      - ALLOW_REFERER=github.com,nodeseek.com